server.port: 8090
#logging.level:
#  root: TRACE
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://keycloak.yadadev.com/auth/realms/my-test
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: gw-test2
            client-secret: c264f5c8-5fed-4da8-aa08-54ebcebe025e
            scope: openid
  cloud:
    gateway:
      routes:
        - id: test-web
          uri: http://pm.lanxinpay.com
          predicates:
            - Path=/app
          filters:
            - OAuth
        - id: test-api
          uri: http://pm.lanxinpay.com
          predicates:
            - Path=/api
          filters:
            - OAuthApi